version: '3'
services:
    database:
        container_name: database
        build: ./database
        ports:
            - '27017:27017' # expose:container
        volumes:
            - ./database/mongodb:/data/db

    backend:
        container_name: backend
        build: ./backend
        ports:
            - '4000:4000'
        volumes:
            - './backend:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on:
            - database
        links:
            - database
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - './frontend:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on:
            - backend
        links:
            - backend
